name: github pages

on:
  push:
    branches:
      - main

permissions:
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add Theme
        uses: docker://plentico/plenti:latest
        with:
          entrypoint: /plenti
          args: theme add https://github.com/plenti-themes/wedding-lite

      - name: Enable Theme
        uses: docker://plentico/plenti:latest
        with:
          entrypoint: /plenti
          args: theme enable wedding-lite

      - name: Build
        uses: docker://plentico/plenti:latest
        with:
          entrypoint: /plenti
          args: build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          FOLDER: public
